### ISSUE TITLE
c/C command variable indexes flipped

### ISSUE THREAD

**Issue by NaridaL** [nfroidure/SVGPathData#19]
The curve command has the first control point in x2/y2 instead of x1/y1 and vice-versa. The expected naming is the same as the SVG standard ( https://www.w3.org/TR/SVG/paths.html#PathDataCubicBezierCommands ). It's not even consistent with the smooth curve command where the second control point is (correctly) in x2/y2.

**Comment by nfroidure** [comment]
Probably due to the way it is parsed and the fact the definition set x and y at the end of the C commands.

https://github.com/nfroidure/SVGPathData/blob/master/src/SVGPathDataParser.js#L233-L248

I have nothing against changing this to fit the standard naming and would merge a PR doing so. It would require a major version bump though.

**Comment by NaridaL** [comment]
Fixed by commit https://github.com/nfroidure/SVGPathData/commit/0ea315275a25006eceb18423c7ceb756f92cc793 .
